# Generated by Django 5.0.3 on 2024-06-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_number_of_people_to_hire_post_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number_of_people_to_hire',
        ),
        migrations.RemoveField(
            model_name='post',
            name='salary',
        ),
    ]
