# Generated by Django 5.0.3 on 2024-06-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_number_of_people_to_hire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_people_to_hire',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.FloatField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
