# Generated by Django 5.0.3 on 2024-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_number_of_people_to_hire_post_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='localisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_people_to_hire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
