# Generated by Django 5.0.4 on 2024-05-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_candidate_cv'),
        ('posts', '0010_post_image_post_localisation_post_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='additional_documents',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='step',
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_img'),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='authentication.candidate'),
        ),
        migrations.AlterField(
            model_name='application',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='posts.post'),
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.candidate')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
