# Generated by Django 5.0.4 on 2024-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_application_additional_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score_matching',
            field=models.IntegerField(default=0),
        ),
    ]
