# Generated by Django 5.0.6 on 2024-06-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0018_application_score_matching"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[("p", "Pending"), ("a", "Accepted"), ("r", "Rejected")],
                default="p",
                max_length=20,
            ),
        ),
    ]
