# Generated by Django 5.0.3 on 2024-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_application_score_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='comp_description',
            field=models.CharField(default=-2024, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='comp_industru',
            field=models.CharField(default=-2024, max_length=100),
            preserve_default=False,
        ),
    ]
