# Generated by Django 5.0.6 on 2024-06-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0019_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
