# Generated by Django 5.0.3 on 2024-06-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_recruiter_comp_description_recruiter_comp_industru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='comp_description',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='comp_industru',
        ),
    ]
