# Generated by Django 5.0.3 on 2024-06-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_remove_recruiter_comp_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='comp_description',
            field=models.CharField(default='No description', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='comp_industry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
