# Generated by Django 5.0.3 on 2024-06-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_recruiter_comp_description_recruiter_comp_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='comp_description',
        ),
    ]
