# Generated by Django 5.0.3 on 2024-06-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_remove_recruiter_comp_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='comp_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
