# Generated by Django 5.0.6 on 2024-06-24 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0020_alter_recruiter_image"),
        ("authentication", "0024_alter_recruiter_comp_description_and_more"),
    ]

    operations = []
