# Generated by Django 5.0.3 on 2024-06-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_merge_20240625_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
