# Generated by Django 5.0.6 on 2024-07-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0025_merge_20240624_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="resume_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
