# Generated by Django 5.0.3 on 2024-06-25 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_recruiter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.recruiter'),
            preserve_default=False,
        ),
    ]
