# Generated by Django 5.0.3 on 2024-06-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_remove_event_event_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='step',
            field=models.CharField(default='Application Review', max_length=20),
        ),
    ]
