# Generated by Django 5.0.3 on 2024-07-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_application_resume_path'),
        ('authentication', '0029_remove_application_status_application_step'),
    ]

    operations = [
    ]
