# Generated by Django 5.0.3 on 2024-07-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_merge_20240705_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
