# Generated by Django 5.0.3 on 2024-07-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='step',
        ),
    ]
