# Generated by Django 5.0.3 on 2024-07-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_remove_application_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='step',
            field=models.CharField(default='Application Review', max_length=20),
        ),
    ]
