# Generated by Django 5.0.4 on 2024-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_intern_datetime_intern_id_internship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='profil',
            field=models.CharField(default='non defined', max_length=255),
        ),
    ]
